apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: agrcwebapi
  name: agrcwebapi
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/agrcwebapi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: agrcwebapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: agrcwebapi
    spec:
      containers:
      - image: gcr.io/exploring-185020/apimapservutahgov:  #minikube won't pull so pull with docker first
        imagePullPolicy: IfNotPresent
        name: agrcwebapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
